const ProductData = [
  {
    id: 1,
    Title: "Apple",
    author: "Marry Enterprices",
    category: "apple",
    img: "./book.jpg",
    price: "₹10",
  },
  {
    id: 2,
    Title: "Mango",
    author: "MN Enterprices",
    category: "mango",
    img: "./book.jpg",
    price: "₹20",
  },
  {
    id: 3,
    Title: "Apple1",
    author: "MN Enterprices",
    category: "apple",
    img: "./book.jpg",
    price: "₹30",
  },
  {
    id: 4,
    Title: "Mango1",
    author: "MN Enterprices",
    category: "mango",
    img: "./book.jpg",
    price: "₹40",
  },
  {
    id: 5,
    Title: "Book5",
    author: "Author5",
    category: "Genre5",
    img: "./book.jpg",
    price: "₹50",
  },
  {
    id: 6,
    Title: "Book6",
    author: "Author6",
    category: "Genre6",
    img: "./book.jpg",
    price: "₹60",
  },
  {
    id: 7,
    Title: "Book7",
    author: "Author7",
    category: "Genre7",
    img: "./book.jpg",
    price: "₹70",
  },
  {
    id: 8,
    Title: "Book8",
    author: "Author8",
    category: "Genre8",
    img: "./book.jpg",
    price: "₹80",
  },
  {
    id: 9,
    Title: "Book9",
    author: "Author9",
    category: "Genre9",
    img: "./book.jpg",
    price: "₹90",
  },
  {
    id: 10,
    Title: "Book10",
    author: "Author10",
    category: "Genre10",
    img: "./book.jpg",
    price: "₹100",
  },
  {
    id: 11,
    Title: "Book11",
    author: "Author11",
    category: "Genre11",
    img: "./book.jpg",
    price: "₹110",
  },
];

export default ProductData;
