const ProductData = [
  {
    id: 1,
    Title: "The Spare Man",
    author: "Mary Robinette Kowal",
    genre: "Genre1",
    img: "./book.jpg",
    price: "₹10",
  },
  {
    id: 2,
    Title: "Book2",
    author: "Author2",
    genre: "Genre2",
    img: "./book.jpg",
    price: "₹20",
  },
  {
    id: 3,
    Title: "Book3",
    author: "Author3",
    genre: "Genre3",
    img: "./book.jpg",
    price: "₹30",
  },
  {
    id: 4,
    Title: "Book4",
    author: "Author4",
    genre: "Genre4",
    img: "./book.jpg",
    price: "₹40",
  },
  {
    id: 5,
    Title: "Book5",
    author: "Author5",
    genre: "Genre5",
    img: "./book.jpg",
    price: "₹50",
  },
  {
    id: 6,
    Title: "Book6",
    author: "Author6",
    genre: "Genre6",
    img: "./book.jpg",
    price: "₹60",
  },
  {
    id: 7,
    Title: "Book7",
    author: "Author7",
    genre: "Genre7",
    img: "./book.jpg",
    price: "₹70",
  },
  {
    id: 8,
    Title: "Book8",
    author: "Author8",
    genre: "Genre8",
    img: "./book.jpg",
    price: "₹80",
  },
  {
    id: 9,
    Title: "Book9",
    author: "Author9",
    genre: "Genre9",
    img: "./book.jpg",
    price: "₹90",
  },
  {
    id: 10,
    Title: "Book10",
    author: "Author10",
    genre: "Genre10",
    img: "./book.jpg",
    price: "₹100",
  },
  {
    id: 11,
    Title: "Book11",
    author: "Author11",
    genre: "Genre11",
    img: "./book.jpg",
    price: "₹110",
  },
];

export default ProductData;
