const ProductData = [
  {
    id: 1,
    Title: "Apple",
    author: "Marry Enterprices",
    category: "apple",
    img: "https://www.freeimages.com/photo/apple-1327789",
    price: 10,
    amount: 1,
  },
  {
    id: 2,
    Title: "Mango",
    author: "MN Enterprices",
    category: "mango",
    img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    price: 20,
    amount: 1,
  },
  {
    id: 3,
    Title: "Apple1",
    author: "MN Enterprices",
    category: "apple",
    img: "./book.jpg",
    price: 30,
    amount: 1,
  },
  {
    id: 4,
    Title: "Mango1",
    author: "MN Enterprices",
    category: "mango",
    img: "./book.jpg",
    price: 40,
    amount: 1,
  },
  {
    id: 5,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
  {
    id: 6,
    Title: "Book6",
    author: "Author6",
    category: "Genre6",
    img: "./book.jpg",
    price: 60,
    amount: 1,
  },
  {
    id: 7,
    Title: "Book7",
    author: "Author7",
    category: "Genre7",
    img: "./book.jpg",
    price: 70,
    amount: 1,
  },
  {
    id: 8,
    Title: "Book8",
    author: "Author8",
    category: "Genre8",
    img: "./book.jpg",
    price: 80,
    amount: 1,
  },
  {
    id: 9,
    Title: "Book9",
    author: "Author9",
    category: "Genre9",
    img: "./book.jpg",
    price: 90,
    amount: 1,
  },
  {
    id: 10,
    Title: "Book10",
    author: "Author10",
    category: "Genre10",
    img: "./book.jpg",
    price: 100,
    amount: 1,
  },
  {
    id: 11,
    Title: "Book11",
    author: "Author11",
    category: "Genre11",
    img: "./book.jpg",
    price: 110,
    amount: 1,
  },
  {
    id: 12,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
  {
    id: 13,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
  {
    id: 14,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
  {
    id: 15,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
  {
    id: 16,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
  {
    id: 17,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
  {
    id: 18,
    Title: "Strawberry",
    author: "Hello Company",
    category: "Strawberry",
    img: "./book.jpg",
    price: 50,
    amount: 1,
  },
];

export default ProductData;
